### PR TITLE
[DEL] partner_name_dutch lives in https://github.com/OCA/l10n-netherlands

### PR DESCRIPTION
**Pull request by hbrunn**
Please only merge this after https://github.com/OCA/l10n-netherlands/pull/3 has been merged

### CODE REVIEW

**Comment by NL66278** [comment]
:+1:  We agreed that this stuff should go into the localization modules

**Comment by StefanRijnhart** [comment]
Conflicts? Try a rebase.

**Comment by hbrunn** [comment]
@StefanRijnhart done

**Comment by StefanRijnhart** [comment]
Thanks!

**Pull request merged**
