### PR TITLE
[ADD] scheduler_mailer_error_therp

### PR DESCRIPTION
**Pull request by gfcapalbo**
Porting to 9.0 the scheduler_mailer_error_therp. Checked v9 of scheduler_mailer_error and no modifications are needed except for version bump.

### CODE REVIEW

**Comment by hbrunn** [comment]
don't forget to assign reviewers here, as otherwise nobody gets a notification.

Please do a standard migration here that lifts commits to the repo

**Review by daramousk — APPROVED** [review]
LGTM

**Review by hbrunn — CHANGES_REQUESTED** [review]
see above

**Review by mFlayyan — APPROVED** [review]

**Comment by NL66278** [comment]
At least one of the errors is caused because travis is still set to version 8.0

**Pull request merged**
