### PR TITLE
7.0 invoice customs

### PR DESCRIPTION
**Pull request by gfcapalbo**
Invoice customs module proposed for merge in main therp branch

### CODE REVIEW

**Comment by hbrunn** [comment]
Is this meant to live here?

**Comment by StefanRijnhart** [comment]
Yes. Just waiting for Giovanni to squash all these commits.

**Comment by StefanRijnhart** [comment]
Giovanni, did you not manage to squash the commits yet?

**Comment by gfcapalbo** [comment]
On 16-01-15 14:57, Stefan Rijnhart (Therp) wrote:

> Giovanni, did you not manage to squash the commits yet?

I tried las week, but could not, i'm sorry for not seing you emails
before, i will also find the time today to look at the pull request on
product_supplier_price_from_invoice, i hadn't seen it on friday, caught
up in the product configurator.

**Pull request closed without merging**
